services:
  radarr-init:
    image: alpine:latest
    container_name: radarr-init
    volumes:
      - ${CONFIG_ROOT}/radarr:/config
      - ${DATA_ROOT}/torrents/movies:/data/torrents
      - ${DATA_ROOT}/media/movies:/movies
    command: >
      sh -c "

        echo 'Fixing permissions for Plex media directories...' &&
        chown -R 1000:1000 /config /data /movies &&
        chmod -R 755 /config /data /movies &&
        echo 'Permissions fixed successfully'
      "

    restart: "no"
    networks:
      - mediaserver
      - registry
  # Movies
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${CONFIG_ROOT}/radarr:/config
      - ${DATA_ROOT}/torrents/movies:/data/torrents
      - ${DATA_ROOT}/media/movies:/movies
    ports:
      - ${RADARR_PORT}:7878
    restart: unless-stopped
    networks:
      - mediaserver
      - registry
    depends_on:
      - radarr-init
  sonarr-init:
    image: alpine:latest
    container_name: sonarr-init
    volumes:
      - ${CONFIG_ROOT}/sonarr:/config
      - ${DATA_ROOT}/torrents/tv:/data/torrents
      - ${DATA_ROOT}/media/tv:/tv
    command: >
      sh -c "

        echo 'Fixing permissions for Plex media directories...' &&
        chown -R 1000:1000 /config /data /tv &&
        chmod -R 755 /config /data /tv &&
        echo 'Permissions fixed successfully'
      "

    restart: "no"
    networks:
      - mediaserver
      - registry
  # TV
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${CONFIG_ROOT}/sonarr:/config
      - ${DATA_ROOT}/torrents/tv:/data/torrents
      - ${DATA_ROOT}/media/tv:/tv
    ports:
      - ${SONARR_PORT}:8989
    restart: unless-stopped
    networks:
      - mediaserver
      - registry
    depends_on:
      - sonarr-init
  # Subtitles
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_ROOT}/bazarr:/config
      - ${DATA_ROOT}/media/movies:/movies
      - ${DATA_ROOT}/media/tv:/tv
    ports:
      - ${BAZARR_PORT}:6767
    restart: unless-stopped
    networks:
      - mediaserver
      - registry
  prowlarr-init:
    image: alpine:latest
    container_name: prowlarr-init
    volumes:
      - ${CONFIG_ROOT}/prowlarr:/config
    command: >
      sh -c "

        echo 'Fixing permissions for Plex media directories...' &&
        chown -R 1000:1000 /config &&
        chmod -R 755 /config &&
        echo 'Permissions fixed successfully'
      "

    restart: "no"
    networks:
      - mediaserver
      - registry
  # Indexer
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${CONFIG_ROOT}/prowlarr:/config
    ports:
      - ${PROWLARR_PORT}:9696
    restart: unless-stopped
    networks:
      - mediaserver
      - registry
    depends_on:
      - prowlarr-init
  qbittorrent-init:
    image: alpine:latest
    container_name: qbittorrent-init
    volumes:
      - ${CONFIG_ROOT}/qbittorrent:/config
      - ${DATA_ROOT}/torrents:/data/torrents
      - ${DATA_ROOT}/torrents/incomplete:/data/incomplete
    command: >
      sh -c "

        echo 'Fixing permissions for Plex media directories...' &&
        chown -R 1000:1000 /config /data &&
        chmod -R 755 /config /data &&
        echo 'Permissions fixed successfully'
      "

    restart: "no"
    networks:
      - mediaserver
      - registry
  # Torrent Client
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=10080
      - TORRENTING_PORT=6881
    volumes:
      - ${CONFIG_ROOT}/qbittorrent:/config
      - ${DATA_ROOT}/torrents:/data/torrents
      - ${DATA_ROOT}/torrents/incomplete:/data/incomplete
    ports:
      - ${QBITTORRENT_WEB_PORT}:10080
      - ${QBITTORRENT_TORRENTING_PORT}:6881
      - ${QBITTORRENT_TORRENTING_PORT}:6881/udp
    restart: unless-stopped
    networks:
      - mediaserver
      - registry
    depends_on:
      - qbittorrent-init
  overseerr-init:
    image: alpine:latest
    container_name: overseerr-init
    volumes:
      - ${CONFIG_ROOT}/overseerr:/config
    command: >
      sh -c "

        echo 'Fixing permissions for Plex media directories...' &&
        chown -R 0:0 /config &&
        chmod -R 755 /config &&
        echo 'Permissions fixed successfully'
      "

    restart: "no"
    networks:
      - mediaserver
      - registry
  # Requesting Web App
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${CONFIG_ROOT}/overseerr:/config
    ports:
      - ${OVERSEERR_PORT}:5055
    restart: unless-stopped
    networks:
      - mediaserver
      - registry
    depends_on:
      - overseerr-init
  # Plex init service to fix permissions
  plex-init:
    image: alpine:latest
    container_name: plex-init
    volumes:
      - ${DATA_ROOT}/media/tv:/tv
      - ${DATA_ROOT}/media/movies:/movies
    command: >
      sh -c "

        echo 'Fixing permissions for Plex media directories...' &&
        chown -R 1000:1000 /tv /movies &&
        chmod -R 755 /tv /movies &&
        echo 'Permissions fixed successfully'
      "

    restart: "no"
    networks:
      - mediaserver
      - registry
  # Media Server
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${CONFIG_ROOT}/plex:/config
      - ${DATA_ROOT}/media/tv:/tv
      - ${DATA_ROOT}/media/movies:/movies
    ports:
      - "32400:32400" # Main Plex port
      - "1900:1900/udp" # DLNA
      - "3005:3005" # Plex Companion
      - "5353:5353/udp" # Bonjour/Avahi
      - "8324:8324" # Plex for Roku
      - "32410:32410/udp" # GDM Network discovery
      - "32412:32412/udp" # GDM Network discovery
      - "32413:32413/udp" # GDM Network discovery
      - "32414:32414/udp" # GDM Network discovery
      - "32469:32469" # DLNA
    restart: unless-stopped
    networks:
      - mediaserver
      - registry
    depends_on:
      - plex-init
    # Note: Plex uses host networking for better performance and compatibility but in rootless mode you cannot use host networking.
  # VPN
  # nordlynx:
  #   image: localhost:5000/ghcr/bubuntux/nordlynx
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #     - PRIVATE_KEY=${NORDLYNX_PRIVATE_KEY}
  #   restart: unless-stopped
  #   networks: host
  #     - default
  #     - registry
networks:
  mediaserver:
    external: true
  registry:
    external: true
