name: smigula-home-server

include:
  - path: services/proxy.yaml
  - path: services/traefik.yaml
  - path: services/mediaserver.yaml
  - path: services/recyclarr.yaml

networks:
  proxy:
    name: traefik_net
    external: true
  internal:
    name: internal_net
  monitoring:
    name: monitoring_net
    external: true
