services:
  # Docker Registry with TLS
  registry:
    image: registry:3
    container_name: registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./config.yaml:/etc/distribution/config.yml:ro
      - ./certs/registry.crt:/etc/ssl/certs/registry.crt:ro
      - ./certs/registry.key:/etc/ssl/private/registry.key:ro
      - registry-data:/var/lib/registry
    env_file:
      - .env
    networks:
      - monitoring
    depends_on:
      - jaeger
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/v2/", "--no-check-certificate"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Jaeger for distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    ports:
      - "16686:16686"  # Jaeger UI - only expose the UI
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - monitoring

  prometheus-init:
    image: alpine:latest
    container_name: prometheus-init
    volumes:
      - prometheus-data:/prometheus
    command: >
      sh -c "
        chown -R 65534:65534 /prometheus &&
        chmod -R 755 /prometheus
      "
    networks:
      - monitoring
    restart: "no"

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"  # Prometheus UI - only expose the UI
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./certs/registry.crt:/etc/prometheus/certs/registry.pem:ro
      - ./certs/registry.key:/etc/prometheus/certs/registry-key.pem:ro
      - ./certs/ca.pem:/etc/prometheus/certs/ca.pem:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
    networks:
      - monitoring
    depends_on:
      - registry
      - prometheus-init

  loki-init:
    image: alpine:latest
    container_name: loki-init
    volumes:
      - loki-data:/loki
    command: >
      sh -c "
        chown -R 10001:10001 /loki &&
        chmod -R 755 /loki
      "
    networks:
      - monitoring
    restart: "no"

  # Loki for log aggregation
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3100/ready"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      - loki-init
  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SERVER_ROOT_URL=https://grafana.smigula.io
    env_file:
      - .env
    networks:
      - monitoring
    depends_on:
      - prometheus
      - jaeger
      - loki

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    secrets:
      - source: users
        target: /data/users.yml
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock
      - dozzle-data:/data
    ports:
      - 9080:9080
    environment:
      - DOZZLE_NO_ANALYTICS=true
      - DOZZLE_ADDR=:9080
      - DOZZLE_HOSTNAME=dozzle.smigula.io
      - DOZZLE_LEVEL=debug
      - DOZZLE_AUTH_PROVIDER=simple
    restart: unless-stopped
    networks:
      - monitoring

  # Grafana Alloy for observability data collection
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - ./caddy/logs:/var/log/caddy:ro
      - alloy-data:/var/lib/alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "12345:12345"
    networks:
      - monitoring
      - caddy_caddy-proxy
      - media_mediaserver

secrets:
  users:
    file: users.yml

volumes:
  registry-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  loki-data:
    driver: local
  dozzle-data:
    driver: local
  alloy-data:
    driver: local

networks:
  monitoring:
    driver: bridge
  media_mediaserver:
    external: true
  caddy_caddy-proxy:
    external: true