services:
  caddy:
    image: localhost:5000/docker/caddy:2.10.0-alpine
    container_name: traefik-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./logs:/var/log/caddy
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - ACME_EMAIL=admin@smigula.io
    networks:
      - traefik-proxy
      - monitoring_monitoring
      - media_mediaserver
      - zot_registry

  landing:
    image: localhost:5000/docker/nginx:alpine
    container_name: landing-page
    restart: unless-stopped
    volumes:
      - ../shared/html:/usr/share/nginx/html:ro
    networks:
      - traefik-proxy
      - zot_registry
    expose:
      - "80"

volumes:
  caddy_data:
    external: false
  caddy_config:
    external: false

networks:
  traefik-proxy:
    driver: bridge
  zot_registry:
    external: true
  monitoring_monitoring:
    external: true
  media_mediaserver:
    external: true
