services:
  postgresql:
    image: registry.smigula.io/docker/postgres:16-alpine
    container_name: authentik-postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ../secrets/all.env.dec
      - .env
    networks:
      - auth
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M
  redis:
    image: registry.smigula.io/docker/redis:8.2.1-alpine
    container_name: authentik-redis
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis-data:/data
    networks:
      - auth
    env_file:
      - ../secrets/all.env.dec
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
        reservations:
          cpus: "0.1"
          memory: 128M
  server:
    image: registry.smigula.io/ghcr/goauthentik/server:2025.6.3
    container_name: authentik-server
    restart: unless-stopped
    command: server
    env_file:
      - ../secrets/all.env.dec
      - .env
    volumes:
      - media-data:/media
      - templates-data:/templates
      - /run/user/1000/docker.sock:/var/run/docker.sock
      - ./dist/custom.css:/web/dist/custom.css
    ports:
      - "${COMPOSE_PORT_HTTP:-9008}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    networks:
      - auth
    depends_on:
      - postgresql
      - redis
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "0.5"
          memory: 512M
  worker:
    image: registry.smigula.io/ghcr/goauthentik/server:2025.6.3
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
    env_file:
      - ../secrets/all.env.dec
      - .env
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock
      - media-data:/media
      - certs-data:/certs
      - templates-data:/templates
      - ./dist/custom.css:/web/dist/custom.css
    networks:
      - auth
    depends_on:
      - postgresql
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
volumes:
  postgres-data:
  redis-data:
  media-data:
  certs-data:
  templates-data:
networks:
  auth:
    external: true
  registry:
    external: true
  traefik:
    external: true
