services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
      - "8082:8082"  # Metrics endpoint
    volumes:
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic:/etc/traefik/dynamic:ro
      - logs-data:/var/log/traefik
      - traefik_certs:/letsencrypt
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
    environment:
      - TRAEFIK_LOG_LEVEL=INFO
    networks:
      - traefik-proxy
      - monitoring_monitoring
      - media_mediaserver
      - zot_registry

  landing:
    image: nginx:alpine
    container_name: landing-page
    restart: unless-stopped
    volumes:
      - ../shared/html:/usr/share/nginx/html:ro
    networks:
      - traefik-proxy
      - zot_registry
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landing.rule=Host(`smigula.io`)"
      - "traefik.http.routers.landing.entrypoints=websecure"
      - "traefik.http.routers.landing.tls.certresolver=letsencrypt"
      - "traefik.http.services.landing.loadbalancer.server.port=80"
      # Redirects
      - "traefik.http.routers.landing.middlewares=landing-redirects"
      - "traefik.http.middlewares.landing-redirects.redirectregex.regex=^https://smigula.io/(grafana|jaeger|registry)$$"
      - "traefik.http.middlewares.landing-redirects.redirectregex.replacement=https://$$1.smigula.io"
      - "traefik.http.middlewares.landing-redirects.redirectregex.permanent=true"

volumes:
  traefik_certs:
    external: false
  logs-data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/data/logs/traefik
      o: bind

networks:
  traefik-proxy:
    driver: bridge
  zot_registry:
    external: true
  monitoring_monitoring:
    external: true
  media_mediaserver:
    external: true