# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/traefik-v3.json
# Static configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  debug: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
  metrics:
    address: ":8082"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@smigula.io
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
      # Uncomment for staging/testing
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory

log:
  level: INFO
  filePath: /var/log/traefik/traefik.log
  format: json

accessLog:
  filePath: /var/log/traefik/access.log
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep

# Enable metrics
metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addServicesLabels: true
    entryPoint: metrics

# OpenTelemetry tracing configuration for Traefik v3
# Temporarily disabled due to editor schema validation issues
tracing:
  serviceName: traefik
  sampleRate: 1.0
  otlp:
    grpc:
      endpoint: alloy:4317
      insecure: true

# Ping for health checks
ping:
  entryPoint: web

experimental:
  plugins:
    traefik-oidc-auth:
      moduleName: "github.com/sevensolutions/traefik-oidc-auth"
      version: "v0.13.0"
    traefik-plugin-geoblock:
      moduleName: "github.com/nscuro/traefik-plugin-geoblock"
      version: "v0.14.0"