distSpecVersion: 1.1.0
storage:
  rootDirectory: /var/lib/zot
  gc: true
http:
  address: 0.0.0.0
  port: '5000'
  externalUrl: https://registry.smigula.io
  auth:
    htpasswd:
      path: /etc/zot/htpasswd
    failDelay: 5s
log:
  level: info
extensions:
  scrub:
    enable: true
    interval: "24h"
  search:
    enable: true
  ui:
    enable: true
  metrics:
    enable: true
    prometheus:
      path: /metrics
  sync:
    enable: true
    credentialsFile: /etc/zot/credentials.yaml
    registries:
      - urls:
          - 'https://registry-1.docker.io'
        onDemand: true
        tlsVerify: true
        maxRetries: 3
        retryDelay: 5m
        content:
          - prefix: '**'
            destination: /docker
      - urls:
          - 'https://ghcr.io'
        onDemand: true
        tlsVerify: true
        maxRetries: 3
        retryDelay: 5m
        content:
          - prefix: '**'
            destination: /ghcr
      - urls:
          - 'https://quay.io'
        onDemand: true
        tlsVerify: true
        content:
          - prefix: '**'
            destination: /quay
      - urls:
          - 'https://registry.k8s.io'
        onDemand: true
        tlsVerify: true
        content:
          - prefix: '**'
            destination: /k8s
      - urls:
          - 'https://gcr.io'
        onDemand: true
        tlsVerify: true
        content:
          - prefix: '**'
            destination: /gcr
