# Credentials for upstream registries
# Uncomment and fill in as needed

# registry-1.docker.io:
#   username: your-docker-username
#   password: your-docker-password

# ghcr.io:
#   username: your-github-username
#   password: your-github-token

# Other registries typically don't require authentication for public images