global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  # Docker Registry metrics
  - job_name: 'zot-registry'
    # scheme: https
    # tls_config:
    #   insecure_skip_verify: true
    #   # Since we're using self-signed certificates, we skip verification
    #   # In production, you would provide CA certificate here:
    #   cert_file: /etc/prometheus/certs/registry.pem
    #   key_file: /etc/prometheus/certs/registry-key.pem
    metrics_path: '/metrics'
    static_configs:
      - targets: ['registry:5000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'zot-registry'
  # Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    metrics_path: '/metrics'
